"""0001_initial

Revision ID: 9875b167c7f9
Revises: 
Create Date: 2026-10-05 21:10:22.617479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9875b167c7f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('html_url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'github_repo_id', name='uq_repositories_user_repo')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress_percent', sa.SmallInteger(), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('hyperparameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('num_topics', sa.SmallInteger(), nullable=True),
    sa.Column('num_issues_fetched', sa.Integer(), nullable=True),
    sa.Column('num_documents', sa.Integer(), nullable=True),
    sa.Column('num_dropped', sa.Integer(), nullable=True),
    sa.Column('vocab_size', sa.Integer(), nullable=True),
    sa.Column('coherence_cv', sa.Float(), nullable=True),
    sa.Column('perplexity', sa.Float(), nullable=True),
    sa.Column('evaluation_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('corpus_stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED', 'FETCHING', 'PREPROCESSING', 'TRAINING', 'ANALYZING', 'COMPLETED', 'FAILED')", name='ck_analyses_status'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_repository_id', 'analyses', ['repository_id'], unique=False)
    op.create_index('ix_analyses_user_id_created_at', 'analyses', ['user_id', 'created_at'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('github_issue_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('created_at_github', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_github', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at_github', sa.DateTime(timezone=True), nullable=True),
    sa.Column('html_url', sa.String(length=1024), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("state IN ('open', 'closed')", name='ck_issues_state'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'github_issue_id', name='uq_issues_repo_issue_id')
    )
    op.create_index('ix_issues_repository_id_number', 'issues', ['repository_id', 'number'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('topic_index', sa.SmallInteger(), nullable=False),
    sa.Column('auto_label', sa.String(length=255), nullable=False),
    sa.Column('human_label', sa.String(length=60), nullable=True),
    sa.Column('prevalence', sa.Float(), nullable=False),
    sa.Column('dominant_issue_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'topic_index', name='uq_topics_analysis_index')
    )
    op.create_table('issue_topic_distributions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.CheckConstraint('probability >= 0.0 AND probability <= 1.0', name='ck_issue_topic_prob'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'issue_id', 'topic_id', name='uq_issue_topic_dist')
    )
    op.create_index('ix_itd_analysis_id_issue_id', 'issue_topic_distributions', ['analysis_id', 'issue_id'], unique=False)
    op.create_index('ix_itd_topic_id_probability', 'issue_topic_distributions', ['topic_id', 'probability'], unique=False)
    op.create_table('topic_words',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'rank', name='uq_topic_words_topic_rank')
    )

    # Enable Row Level Security (RLS) on all tables for Supabase PostgreSQL (PRD §10, D-21)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY;")
        op.execute("ALTER TABLE repositories ENABLE ROW LEVEL SECURITY;")
        op.execute("ALTER TABLE issues ENABLE ROW LEVEL SECURITY;")
        op.execute("ALTER TABLE analyses ENABLE ROW LEVEL SECURITY;")
        op.execute("ALTER TABLE topics ENABLE ROW LEVEL SECURITY;")
        op.execute("ALTER TABLE topic_words ENABLE ROW LEVEL SECURITY;")
        op.execute("ALTER TABLE issue_topic_distributions ENABLE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_words')
    op.drop_index('ix_itd_topic_id_probability', table_name='issue_topic_distributions')
    op.drop_index('ix_itd_analysis_id_issue_id', table_name='issue_topic_distributions')
    op.drop_table('issue_topic_distributions')
    op.drop_table('topics')
    op.drop_index('ix_issues_repository_id_number', table_name='issues')
    op.drop_table('issues')
    op.drop_index('ix_analyses_user_id_created_at', table_name='analyses')
    op.drop_index('ix_analyses_repository_id', table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
