"""Protected technical terms and casing rules for GitIssue."""

PROTECTED_TERMS: set[str] = {
    "cuda",
    "cudnn",
    "gpu",
    "cpu",
    "tpu",
    "tensorflow",
    "pytorch",
    "keras",
    "numpy",
    "pandas",
    "sklearn",
    "python",
    "java",
    "javascript",
    "typescript",
    "rust",
    "golang",
    "docker",
    "kubernetes",
    "linux",
    "windows",
    "macos",
    "ios",
    "android",
    "npm",
    "pip",
    "conda",
    "git",
    "github",
    "api",
    "sdk",
    "cli",
    "gui",
    "json",
    "yaml",
    "xml",
    "http",
    "https",
    "ssl",
    "tls",
    "sql",
    "aws",
    "gcp",
    "azure",
    "onnx",
    "llm",
    "nan",
}

DISPLAY_CASE: dict[str, str] = {
    "gpu": "GPU",
    "cuda": "CUDA",
    "cudnn": "cuDNN",
    "cpu": "CPU",
    "tpu": "TPU",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "keras": "Keras",
    "numpy": "NumPy",
    "pandas": "Pandas",
    "sklearn": "scikit-learn",
    "python": "Python",
    "java": "Java",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "rust": "Rust",
    "golang": "Go",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "linux": "Linux",
    "windows": "Windows",
    "macos": "macOS",
    "ios": "iOS",
    "android": "Android",
    "npm": "npm",
    "pip": "pip",
    "conda": "Conda",
    "git": "Git",
    "github": "GitHub",
    "api": "API",
    "sdk": "SDK",
    "cli": "CLI",
    "gui": "GUI",
    "json": "JSON",
    "yaml": "YAML",
    "xml": "XML",
    "http": "HTTP",
    "https": "HTTPS",
    "ssl": "SSL",
    "tls": "TLS",
    "sql": "SQL",
    "aws": "AWS",
    "gcp": "GCP",
    "azure": "Azure",
    "onnx": "ONNX",
    "llm": "LLM",
    "nan": "NaN",
}


def display_case(word: str) -> str:
    """Format word with display casing if protected, else capitalize."""
    w = word.strip().lower()
    if w in DISPLAY_CASE:
        return DISPLAY_CASE[w]
    return w.capitalize()
